-- Create the budgets table (if not exists)
create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null,
  status text not null default 'pending'::text,
  constraint budgets_status_check check (status in ('pending', 'contacted', 'completed'))
);

-- Enable Row Level Security (RLS)
alter table public.budgets enable row level security;

-- Drop existing policies if any
drop policy if exists "Allow anonymous insert" on public.budgets;
drop policy if exists "Allow service role to read all records" on public.budgets;
drop policy if exists "Allow service role to update all records" on public.budgets;
drop policy if exists "Enable update for authenticated users" on public.budgets;

-- Create policy to allow anonymous insert
create policy "Allow anonymous insert"
on public.budgets
for insert
to anon
with check (true);

-- Create policy to allow authenticated users to read all budgets
create policy "Allow authenticated read"
on public.budgets
for select
to authenticated
using (true);

-- Create policy to allow anonymous read
create policy "Allow anonymous read"
on public.budgets
for select
to anon
using (true);

-- Create policy to allow anonymous updates
create policy "Allow anonymous update"
on public.budgets
for update
to anon
using (true)
with check (true);

-- Grant necessary permissions
grant usage on schema public to anon, authenticated;
grant all on public.budgets to anon, authenticated; 